# action.yml
name: AI Reviewer
description: Comment from AI

# GitHub Marketplace - Branding
branding:
  icon: "terminal"
  color: "black"

# Input parameters
inputs:
  ANTHROPIC_API_KEY:
    description: "Anthropic Studio API Key"

# Action steps
runs:
  using: "composite"
  steps:
    - name: Get PR diff, run AI review, and comment
      id: ai-review
      shell: bash
      run: node ${GITHUB_ACTION_PATH}/dist/index.cjs
      env:
        ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
